### ISSUE TITLE
Stripe.js

### ISSUE THREAD

**Issue by ghost** [oskarrough/nkflohmarkt#13]
First things, logins to access dashboard are ida.neukolln@gmail.com.

There is a cool feature named "checkout client" (https://stripe.com/docs/payments/checkout/client) that allows to define products in the dashboard (eg stand_individual, stand_business) + client side snippets to display the form. Example here: https://bit.ly/2uFhqb3. So no backend needed.

The problem is that when I want to configure those products, we should _"Before you start configuring products, first make sure you are in test mode by toggling the “View test data” button at the bottom of your dashboard menu"._ But for this we need to activate the account,and so adding all data (name, bank account etc.).

**Comment by oskarrough** [comment]
Great! I'll get the details added to the account.

**Comment by ghost** [comment]
Or API approach!

- custom form on front
- then fetch post() data to "XXXX/api/tokens" routes in Node server
- In node server, do the payment with handleCardPayment() (https://stripe.com/docs/stripe-js/reference#stripe-handle-card-payment).

**Comment by oskarrough** [comment]
That's also great buuut then we'd have to be willing to maintain it... so I think your no-backend idea above sounds better.
